### ISSUE TITLE
ComfyUI error

### ISSUE THREAD

**Issue by vitacon** [thomaseding/sd-webui-color-enhance#1]
Hello,
can you please suggest a solution for this error?

```
ToDtype.__init__() got an unexpected keyword argument 'scale'
(...)
edited_image = v2.ToDtype(dtype=torch.uint8, scale=True)(img).squeeze()

```
`import torchvision.transforms.v2 as v2`

Does it require a different version of TorchVision?

![image](https://github.com/thomaseding/sd-webui-color-enhance/assets/58292841/3a68c9cb-990c-4bc9-a83a-77fc4019f040)

**Comment by thomaseding** [comment]
My repository is a fork. Please submit to the original repo

**Comment by vitacon** [comment]
I see -  I thought both repositories were maintained by the same person.
